import { useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, Check, Clock3, MapPin, MessageCircle, Share2, Store, Tag } from 'lucide-react'
import type { Coordinates } from '../lib/geo'
import { distanceKm } from '../lib/geo'
import type { Product } from '../types/database'

export type Shop = { id: string; name: string; description?: string | null; category: string; address: string; locality: string; city: string; phone?: string | null; logo_url?: string | null; cover_url?: string | null; latitude?: number | null; longitude?: number | null; is_open?: boolean; opening_hours?: Record<string, { open?: string; close?: string; closed?: boolean }> }
export function ShopOpenStatus({shop}:{shop:Shop}){if(shop.is_open===false)return <small className="opening-status closed">Closed</small>;const key=new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date()).toLowerCase();const today=shop.opening_hours?.[key];if(!today||today.closed)return <small className="opening-status closed">Closed</small>;const now=new Date().toTimeString().slice(0,5);const open=Boolean(today.open&&today.close&&now>=today.open&&now<today.close);return <small className={`opening-status ${open?'open':'closed'}`}>{open?'Open':'Closed'}</small>}
export function StockBadge({ quantity }: { quantity: number }) { const kind = quantity < 1 ? 'out' : quantity <= 3 ? 'limited' : 'in'; return <span className={`stock-badge ${kind}`}>{kind === 'out' ? 'OUT OF STOCK' : kind === 'limited' ? 'LIMITED STOCK' : 'IN STOCK'}</span> }
export function ShareButton({ title, url, compact = false }: { title: string; url?: string; compact?: boolean }) {
 const [copied, setCopied] = useState(false)
 async function share() { const link = url ?? window.location.href; if (navigator.share) { try { await navigator.share({ title, url: link }) } catch { /* share sheet closed */ } } else { try { if (navigator.clipboard) await navigator.clipboard.writeText(link); else { const field=document.createElement('textarea'); field.value=link; field.style.position='fixed'; field.style.opacity='0'; document.body.append(field); field.select(); document.execCommand('copy'); field.remove() } setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { window.prompt('Copy this link', link) } } }
 return <button className="icon-action" type="button" onClick={() => void share()} aria-label={`Share ${title}`} title={copied ? 'Link copied' : 'Share'}>{copied ? <Check size={16}/> : <Share2 size={16}/>} {!compact && <span>{copied ? 'Copied' : 'Share'}</span>}</button>
}
export function ProductCard({ product, index = 0 }: { product: Product; index?: number }) { const image = product.image_urls?.[0] || product.image_url; return <Link to={`/products/${product.id}`} className="product-card"><div className={`product-image product-tone-${index % 4}`}>{image ? <img src={image} alt={product.name}/> : <span>{product.category?.slice(0, 1) || '✳'}</span>}<StockBadge quantity={product.stock_quantity}/></div><div className="product-info"><small><Tag size={12}/> {product.category}</small><h3>{product.name}</h3><p><MapPin size={13}/> {product.shops?.name || 'Neighborhood shop'} · {product.shops?.locality || 'Nearby'}</p><div className="product-card-bottom"><strong>₹{Number(product.price).toLocaleString('en-IN')}</strong><ArrowUpRight size={15}/></div></div></Link> }
export function ShopCard({ shop, location }: { shop: Shop; location?: Coordinates | null }) { const km = location && shop.latitude != null && shop.longitude != null ? distanceKm(location, { latitude: shop.latitude, longitude: shop.longitude }) : null; const image=shop.cover_url||shop.logo_url; return <Link className="shop-card" to={`/shops/${shop.id}`}><div className="shop-card-mark">{image ? <img src={image} alt=""/> : <Store size={21}/>}</div><div className="shop-card-copy"><h3>{shop.name}</h3><p>{shop.category} · {shop.locality}</p><small><MapPin size={12}/>{km == null ? shop.locality : `${km.toFixed(1)} km away`}</small><ShopOpenStatus shop={shop}/></div><ArrowUpRight size={16}/></Link> }
export function SearchBar({ value, onChange, placeholder = 'Search products, categories or shops' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="search-bar"><span className="sr-only">Search</span><span className="search-glass">⌕</span><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder}/>{value && <button type="button" className="clear-search" onClick={() => onChange('')}>Clear</button>}</label> }
export function CategoryFilter({ value, onChange, categories }: { value: string; onChange: (value: string) => void; categories: string[] }) { return <label className="filter-control">Category<select value={value} onChange={event => onChange(event.target.value)}><option value="">All categories</option>{categories.map(item => <option key={item}>{item}</option>)}</select></label> }
export function PriceFilter({ min, max, onMin, onMax }: { min: string; max: string; onMin: (value: string) => void; onMax: (value: string) => void }) { return <div className="filter-control price-filter"><span>Price</span><div><input type="number" min="0" aria-label="Minimum price" placeholder="Min ₹" value={min} onChange={event => onMin(event.target.value)}/><input type="number" min="0" aria-label="Maximum price" placeholder="Max ₹" value={max} onChange={event => onMax(event.target.value)}/></div></div> }
export function ProductImageGallery({ images, name }: { images: string[]; name: string }) { const [selected, setSelected] = useState(0); return <div className="gallery"><div className="gallery-main">{images[selected] ? <img src={images[selected]} alt={`${name} ${selected + 1}`}/> : <span>{name.slice(0, 1)}</span>}</div>{images.length > 1 && <div className="gallery-thumbs">{images.map((url, index) => <button type="button" key={`${url}-${index}`} className={selected === index ? 'selected' : ''} onClick={() => setSelected(index)} aria-label={`Show image ${index + 1}`}><img src={url} alt=""/></button>)}</div>}</div> }
export function VariantSelector({ variants, value, onChange }: { variants: { id: string; name: string; stock_quantity: number; price: number | null }[]; value: string; onChange: (value: string) => void }) { if (!variants.length) return null; return <label className="variant-picker">Choose size or variant<select value={value} onChange={event => onChange(event.target.value)}><option value="">Select an option</option>{variants.map(variant => <option key={variant.id} value={variant.id} disabled={!variant.stock_quantity}>{variant.name}{variant.price != null ? ` · ₹${Number(variant.price).toLocaleString('en-IN')}` : ''}{!variant.stock_quantity ? ' · Out of stock' : ''}</option>)}</select></label> }
export function InquiryCard({ title, status, message, createdAt, onOpen }: { title: string; status: string; message: string; createdAt: string; onOpen?: () => void }) { return <article className="activity-card"><div className="activity-icon"><MessageCircle size={17}/></div><div className="activity-main"><h3>{title}</h3><p>{message}</p><small>{new Date(createdAt).toLocaleString()}</small></div><span className={`status-pill ${status}`}>{status.replace('_', ' ')}</span>{onOpen && <button onClick={onOpen} className="button secondary">Open chat</button>}</article> }
export function MessageBubble({ body, createdAt, own, unread }: { body: string; createdAt: string; own: boolean; unread?: boolean }) { return <div className={`message-row ${own ? 'own' : ''}`}><div className="message-bubble">{body}<small><Clock3 size={11}/> {new Date(createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}{unread && <span> · New</span>}</small></div></div> }
export function ChatWindow({ children, title, subtitle }: { children: ReactNode; title: string; subtitle?: string }) { return <section className="chat-window"><header><div className="shop-card-mark"><Store size={18}/></div><div><h2>{title}</h2><small>{subtitle || 'Local shop conversation'}</small></div></header>{children}</section> }
export function ReservationCard({ title, shop, quantity, status, time, pickup, onCancel }: { title: string; shop: string; quantity: number; status: string; time: string; pickup?: string | null; onCancel?: () => void }) { return <article className="activity-card"><div className="activity-icon"><Store size={17}/></div><div className="activity-main"><h3>{title}</h3><p>{shop} · Quantity {quantity}</p><small>Requested {new Date(time).toLocaleString()}{pickup ? ` · Pickup ${new Date(pickup).toLocaleString()}` : ''}</small></div><span className={`status-pill ${status}`}>{status}</span>{status === 'requested' && onCancel && <button className="text-button" onClick={onCancel}>Cancel</button>}</article> }
export function NotificationItem({ title, body, createdAt, unread, onRead }: { title: string; body: string; createdAt: string; unread: boolean; onRead: () => void }) { return <button className={`notification-item ${unread ? 'unread' : ''}`} onClick={onRead}><span className="notification-dot"/><span><b>{title}</b><small>{body}</small><time>{new Date(createdAt).toLocaleString()}</time></span>{unread && <span className="status-pill new">NEW</span>}</button> }
export function LoadingSkeleton({ rows = 3 }: { rows?: number }) { return <div className="skeleton-list" aria-label="Loading">{Array.from({ length: rows }, (_, i) => <div className="skeleton" key={i}/>)}</div> }
export function EmptyState({ title, message, action }: { title: string; message: string; action?: ReactNode }) { return <div className="empty-card customer-empty"><div className="empty-icon"><Store size={21}/></div><h3>{title}</h3><p>{message}</p>{action}</div> }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="inline-error" role="alert">{message}{retry && <button onClick={retry} className="text-button">Retry</button>}</div> }
export function SuccessState({ message }: { message: string }) { return <p className="success-message" role="status">{message}</p> }
export function ConfirmationDialog({ open, title, message, confirmLabel = 'Confirm', onConfirm, onCancel }: { open: boolean; title: string; message: string; confirmLabel?: string; onConfirm: () => void; onCancel: () => void }) { if (!open) return null; return <div className="dialog-backdrop" role="presentation"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">{title}</h2><p>{message}</p><div><button className="button secondary" onClick={onCancel}>Keep it</button><button className="button primary" onClick={onConfirm}>{confirmLabel}</button></div></section></div> }
export function Toast({ message, onClose }: { message: string; onClose: () => void }) { if (!message) return null; return <div className="toast" role="status">{message}<button onClick={onClose} aria-label="Dismiss">×</button></div> }
export function ChatLink({ id }: { id: string }) { return <Link className="button secondary" to={`/chat/${id}`}>Open chat <MessageCircle size={15}/></Link> }
